import Head from "next/head";
import Link from "next/link";
import { SignUp } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";



import { api } from "import/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />

      </main>
    </>
  );
}
